version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 5657:6379
    networks:
      - achievements_network
  postgres:
    image: postgres:10.14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: achievements
    ports:
      - 5656:5432
    networks:
      - achievements_network

networks:
  achievements_network:
    ipam:
      driver: default
      config:
        - subnet: '10.0.3.0/24'
